
name: Fetch RSS Feed and Update Repo

on:
  schedule:
    - cron: '0 0 * * *'  # This will run every hour
  workflow_dispatch:  # Manual trigger option

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
          pip install requests

      - name: Install System Dependencies
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
  
      - name: Install Ollama
        run: |
          echo "Installing Ollama CLI..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
  
      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          ollama serve &
          sleep 5  # Allow time for the service to initialize
  
      - name: Verify Ollama Service
        run: |
          echo "Checking if Ollama API is running..."
          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
  
      - name: Pull LLaMA Model
        run: |
          echo "Pulling the LLaMA 2 model..."
          if ! ollama pull llama3; then
            echo "Model pull failed. Please check model availability or permissions."
            exit 1
          fi

      - name: Fetch RSS feed and store data
        run: |
          set +e  # Allow the script to continue on errors
          python fetch_rss.py
          if [ $? -ne 0 ]; then
            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
          fi
          set -e  # Re-enable stopping on errors
      - name: Commit and push updated RSS data and GUIDs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rss_data.json guids.json
          git commit -m "Update RSS feed data and GUIDs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  update-rss1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Install System Dependencies
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
  
      - name: Install Ollama
        run: |
          echo "Installing Ollama CLI..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
  
      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          ollama serve &
          sleep 5  # Allow time for the service to initialize
  
      - name: Verify Ollama Service
        run: |
          echo "Checking if Ollama API is running..."
          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
  
      - name: Pull LLaMA Model
        run: |
          echo "Pulling the LLaMA 2 model..."
          if ! ollama pull llama3; then
            echo "Model pull failed. Please check model availability or permissions."
            exit 1
          fi

      - name: Fetch RSS feed and store data
        run: |
          set +e  # Allow the script to continue on errors
          python fetch_rss1.py
          if [ $? -ne 0 ]; then
            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
          fi
          set -e  # Re-enable stopping on errors

  update-rss2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Install System Dependencies
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
  
      - name: Install Ollama
        run: |
          echo "Installing Ollama CLI..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
  
      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          ollama serve &
          sleep 5  # Allow time for the service to initialize
  
      - name: Verify Ollama Service
        run: |
          echo "Checking if Ollama API is running..."
          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
  
      - name: Pull LLaMA Model
        run: |
          echo "Pulling the LLaMA 2 model..."
          if ! ollama pull llama3; then
            echo "Model pull failed. Please check model availability or permissions."
            exit 1
          fi

      - name: Fetch RSS feed and store data
        run: |
          set +e  # Allow the script to continue on errors
          python fetch_rss2.py
          if [ $? -ne 0 ]; then
            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
          fi
          set -e  # Re-enable stopping on errors
  update-rss3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Install System Dependencies
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
  
      - name: Install Ollama
        run: |
          echo "Installing Ollama CLI..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
  
      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          ollama serve &
          sleep 5  # Allow time for the service to initialize
  
      - name: Verify Ollama Service
        run: |
          echo "Checking if Ollama API is running..."
          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
  
      - name: Pull LLaMA Model
        run: |
          echo "Pulling the LLaMA 2 model..."
          if ! ollama pull llama3; then
            echo "Model pull failed. Please check model availability or permissions."
            exit 1
          fi

      - name: Fetch RSS feed and store data
        run: |
          set +e  # Allow the script to continue on errors
          python fetch_rss3.py
          if [ $? -ne 0 ]; then
            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
          fi
          set -e  # Re-enable stopping on errors
      - name: Commit and push updated RSS data and GUIDs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rss_data.json guids.json
          git commit -m "Update RSS feed data and GUIDs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  update-rss4:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Install System Dependencies
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
  
      - name: Install Ollama
        run: |
          echo "Installing Ollama CLI..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
  
      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          ollama serve &
          sleep 5  # Allow time for the service to initialize
  
      - name: Verify Ollama Service
        run: |
          echo "Checking if Ollama API is running..."
          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
  
      - name: Pull LLaMA Model
        run: |
          echo "Pulling the LLaMA 2 model..."
          if ! ollama pull llama3; then
            echo "Model pull failed. Please check model availability or permissions."
            exit 1
          fi

      - name: Fetch RSS feed and store data
        run: |
          set +e  # Allow the script to continue on errors
          python fetch_rss4.py
          if [ $? -ne 0 ]; then
            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
          fi
          set -e  # Re-enable stopping on errors
      - name: Commit and push updated RSS data and GUIDs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rss_data.json guids.json
          git commit -m "Update RSS feed data and GUIDs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}


  update-rss5:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Install System Dependencies
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
  
      - name: Install Ollama
        run: |
          echo "Installing Ollama CLI..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
  
      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          ollama serve &
          sleep 5  # Allow time for the service to initialize
  
      - name: Verify Ollama Service
        run: |
          echo "Checking if Ollama API is running..."
          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
  
      - name: Pull LLaMA Model
        run: |
          echo "Pulling the LLaMA 2 model..."
          if ! ollama pull llama3; then
            echo "Model pull failed. Please check model availability or permissions."
            exit 1
          fi

      - name: Fetch RSS feed and store data
        run: |
          set +e  # Allow the script to continue on errors
          python fetch_rss5.py
          if [ $? -ne 0 ]; then
            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
          fi
          set -e  # Re-enable stopping on errors
      - name: Commit and push updated RSS data and GUIDs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rss_data.json guids.json
          git commit -m "Update RSS feed data and GUIDs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  update-rss6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Install System Dependencies
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
  
      - name: Install Ollama
        run: |
          echo "Installing Ollama CLI..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
  
      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          ollama serve &
          sleep 5  # Allow time for the service to initialize
  
      - name: Verify Ollama Service
        run: |
          echo "Checking if Ollama API is running..."
          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
  
      - name: Pull LLaMA Model
        run: |
          echo "Pulling the LLaMA 2 model..."
          if ! ollama pull llama3; then
            echo "Model pull failed. Please check model availability or permissions."
            exit 1
          fi

      - name: Fetch RSS feed and store data
        run: |
          set +e  # Allow the script to continue on errors
          python fetch_rss6.py
          if [ $? -ne 0 ]; then
            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
          fi
          set -e  # Re-enable stopping on errors
      - name: Commit and push updated RSS data and GUIDs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rss_data.json guids.json
          git commit -m "Update RSS feed data and GUIDs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  update-rss7:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser

      - name: Install System Dependencies
        run: |
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer imagemagick ghostscript curl jq
  
      - name: Install Ollama
        run: |
          echo "Installing Ollama CLI..."
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version
  
      - name: Start Ollama Service
        run: |
          echo "Starting Ollama service..."
          ollama serve &
          sleep 5  # Allow time for the service to initialize
  
      - name: Verify Ollama Service
        run: |
          echo "Checking if Ollama API is running..."
          curl http://127.0.0.1:11434/ || (echo "Ollama service not responding" && exit 1)
  
      - name: Pull LLaMA Model
        run: |
          echo "Pulling the LLaMA 2 model..."
          if ! ollama pull llama3; then
            echo "Model pull failed. Please check model availability or permissions."
            exit 1
          fi

      - name: Fetch RSS feed and store data
        run: |
          set +e  # Allow the script to continue on errors
          python fetch_rss7.py
          if [ $? -ne 0 ]; then
            echo "Error occurred while running fetch_rss.py. Continuing with other tasks..."
          fi
          set -e  # Re-enable stopping on errors
      - name: Commit and push updated RSS data and GUIDs
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add rss_data.json guids.json
          git commit -m "Update RSS feed data and GUIDs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
